---
# Configuration file for MegaLinter
# See all available variables at
# https://megalinter.io/configuration/ and in linters documentation
VALIDATE_ALL_CODEBASE: true
VALIDATE_EDITORCONFIG: false
DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - REPOSITORY_DEVSKIM
  - PYTHON_FLAKE8
  - BASH_SHELLCHECK
  - SPELL_LYCHEE
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - CSS_STYLELINT
  - HTML_DJLINT
  - HTML_HTMLHINT
  - C_CLANG_FORMAT
  - CPP_CLANG_FORMAT
  - C_CPPLINT
  - CPP_CPPLINT
  - SPELL_CSPELL
  - PERL_PERLCRITIC
